apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup-cronjob
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: my-backup-image
            command: ["/bin/sh", "-c", "backup.sh"]
          restartPolicy: OnFailure
