apiVersion: v1
kind: Pod
metadata:
  name: tomcat-test
  namespace: default
  labels:
    app:  tomcat
spec:
  containers:
  - name:  tomcat
    ports:
    - containerPort: 8080  
    image: tomcat    #镜像
    imagePullPolicy: IfNotPresent
