apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
     app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None             #statefullset的service的ip设置成none没有ip
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet             #资源类型  statefullset   这个资源适合创建有状态的服务,比如说像mysql  名字不能随便更换，statefulset创建的pod名字也会有序号排列
                              #比如说web-1这个pod突然挂掉了之后重启的时候还是原来的web-1这个名字
metadata:
  name: web
spec:
  selector:
    matchLabels:                #标签选择器
      app: nginx
  serviceName: "nginx"          #选择service
  replicas: 2                   #副本数,之后创建出来的pod就是pod名字-0  pod名字-1
  template:
    metadata:
     labels:
       app: nginx
    spec:
      containers:
      - name: nginx
        image: 192.168.8.99/web/nginx:1.26
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:       #statfullset的pvc模板，pod都是基于这个模板的pvc挂载到pod里面的目录
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]        #访问权限
      storageClassName: "nfs"               #pvc基于动态存储类自动创建
      resources:
        requests:
          storage: 1Gi                      #每个pvc的容量是1G